spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    password: saidur
    url: jdbc:postgresql://localhost:5432/people_pilot
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
