spring:
  profiles:
    active: dev
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    password: configure_in_application-dev
    url: configure_in_application-dev
    username: configure_in_application-dev


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
